# Generated by Django 2.0.7 on 2018-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=100)),
            ],
        ),
    ]
